get:
  tags:
    - Configurations
  summary: Get configuration
  description: Retrieves the full configuration for a given environment. Config values are displayed hierarchically as a tree
  operationId: getConfiguration
  responses:
    "200 Ok":
      description: Configuration retrieved successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Configuration"
    "404 Not found":
      description: Application or Environment not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            "Application not empty":
              value:
                code: not_found
                message: Resource not found
post:
  tags:
    - Configurations
  summary: Create configuration
  description: Creates a new configuration under the given environment
  operationId: createConfiguration
  requestBody:
    description: Create a new configuration
    content:
      application/json:
        schema:
          type: object
          properties:
            properties:
              type: string
              format: json
              example:
                key1: value1
                key2: value2
    required: true
  responses:
    "201 Created":
      description: Configuration created successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Configuration"
    "400 Bad request":
      description: Invalid request body
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            "Invalid config format":
              value:
                code: invalid_config_format
                message: Invalid config format. Check the payload
    "404 Not found":
      description: Application or Environment not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            "Application not empty":
              value:
                code: not_found
                message: Resource not found
delete:
  tags:
    - Configurations
  summary: Delete configuration
  description: Remove all properties from an existing configuration
  operationId: deleteConfiguration
  responses:
    "204 No content":
      description: Configuration deleted successfully
    "404 Not found":
      description: Application or Environment not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            "Application not empty":
              value:
                code: not_found
                message: Resource not found
