# Docker compose setup for local development (Dependencies only)
version: "3.8"
services:
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=configmonkey
      - POSTGRES_PASSWORD=configmonkey
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional (For viewing/managing the db)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
