openapi: 3.0.3
info:
  title: Configmonkey - API Reference
  version: 0.0.1
  description: >
    # Overview

    Configmonkey's data architecture is structured in three main entities/resources: `Applications`, `Environments` and 
    `Configurations`, the first two describing the context where each individual set of configuration values lives, The
    hierarchy follows the scheme: `Application > Environment > Configuration`. Therefore, creating or accessing `Configurations`
    assumes knowledge of an `Application` and `Environment` which were previously setup.

    ## Applications

    As the name suggests, we recommend that users match this resource with the program they're adding to Configmokey. `Applications`
    are the root level container and they can have multiple `Environments`.

    ## Environments

    We recommend mirroring the number of environments 1:1, with each individual deployment of the application (e.g. Production,
    Staging, Development), however  the API doesn't enforce it since it knows nothing about the semantics of `Environments`, 
    except that there can be more than one and they can have only one `Application`.

    ## Configurations

    The leaf node of the configuration hierarchy. Each `Configuration` belongs to one `Environment`, and there can be only one 
    per `Environment`. `Configurations` are hierarchical and support multiple variables and groups of variables, structured in a tree
    data structure pretty much like a JSON file.

tags:
  - name: Applications
    description: CRUD over aplications
  - name: Environments
    description: CRUD over environments
  - name: Configurations
    description: CRUD over configurations
paths:
  /v1/apps:
    $ref: "./paths/apps.yaml"
  /v1/apps/{app_slug}:
    $ref: "./paths/apps-by-slug.yaml"
  /v1/envs/{app_slug}:
    parameters:
      - $ref: "#/components/parameters/ApplicationSlug"
    $ref: "./paths/envs.yaml"
  /v1/envs/{app_slug}/{env_slug}:
    parameters:
      - $ref: "#/components/parameters/ApplicationSlug"
      - $ref: "#/components/parameters/EnvironmentSlug"
    $ref: "./paths/envs-by-slug.yaml"
  /v1/configs/{app_slug}/{env_slug}:
    parameters:
      - $ref: "#/components/parameters/ApplicationSlug"
      - $ref: "#/components/parameters/EnvironmentSlug"
    $ref: "./paths/configs.yaml"
components:
  parameters:
    $ref: "./parameters.yaml"
  schemas:
    $ref: "./schemas.yaml"
