name: Main Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Start dependencies
        run: docker-compose -f "docker-compose.yaml" up -d --build

      - name: Run Tests
        run: cargo test

      - name: Stop dependencies
        if: always()
        run: docker-compose -f "docker-compose.yaml" down
